import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';


export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

export default function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            <section className="bg-gray-50 dark:bg-gray-900">
                <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto h-screen lg:py-0">
            {children}
                </div>
            </section>
        </>
    );
}
