import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';


export const metadata: Metadata = {
    title: 'Login',
    description: 'Generated by create next app',
};

export default function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <>
            <h1>Auth layout</h1>
            {children}
        </>
    );
}
