import Profile from '@/app/dashboard/profile/profile';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Profile',
    description: 'Generated by create next app',
};

export default async function Page() {
    return (
        <div className="flex flex-col items-center justify-center mx-auto min-h-full">
            <Profile />
        </div>
    );
}