import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ThemeProvider from '@/lib/providers/theme-provider';
import QueryClientProvider from '@/lib/providers/query-client-provider';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html suppressHydrationWarning lang="en">
            <body className={inter.className}>
                <QueryClientProvider>
                    <ThemeProvider>
                        <Toaster position="top-center" toastOptions={{
                            style: {
                                borderRadius: '2px',
                            }
                        }}  />
                        {children}
                    </ThemeProvider>
                </QueryClientProvider>
            </body>
        </html>
    );
}
