import { Metadata } from 'next';
import Settings from '@/app/dashboard/settings/settings';

export const metadata: Metadata = {
    title: 'Settings',
    description: 'Generated by create next app',
};

export default async function SettingsPage() {
    return (
        <Settings />
    )
}