import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { createClient } from '@/lib/utils/supabase/server';
import { redirect } from 'next/navigation';
import DashboardNav from '@/app/dashboard/(components)/dashboard-nav';
import DashboardSidebar from '@/app/dashboard/(components)/dashboard-sidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function Layout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    const cookieStore = cookies();
    const supabase = createClient(cookieStore);

    const {
        data: { session },
        error: sessionError
    } = await supabase.auth.getSession();

    if (sessionError || !session) {
        redirect('/login');
    }

    if (session) {
        const { data: profile, error } = await supabase.from('profiles').select('*').eq('id', session.user?.id);

        if (error || !session?.user) {
            redirect('/login');
        }

        return (
            <section className="bg-gray-50 dark:bg-gray-900">
                <div className="min-h-screen">
                    <div className="text-gray-900 dark:text-white">
                        <div className="relative">
                            <DashboardSidebar />
                            <main className="pl-52">
                                <DashboardNav user={session.user} userProfile={profile[0]} />
                                <div className="p-4 h-[calc(100vh-65px)]">
                                    {children}
                                </div>
                            </main>
                        </div>
                    </div>
                </div>
            </section>
        );
    }

    return null;
}
