import { Metadata } from 'next';
import Log from '@/app/dashboard/log/log';

export const metadata: Metadata = {
    title: 'Log',
    description: 'Generated by create next app',
};

export default async function Page() {
    return (
        <div className="min-h-full">
            <Log />
        </div>
    );
}