import Workouts from '@/app/dashboard/workouts/workouts';
import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Workouts',
    description: 'Generated by create next app',
};

export default function DashboardWorkoutsPage() {
    return (
        <Workouts />
    )
}